### ISSUE TITLE
How do I remigrate a database?

### ISSUE THREAD

**Issue by endrebak** [yogthos/migratus#101]
Completely new to web-programming here, so thanks for your patience.

Created my project with `lein new luminus rnadb +h2`, which means that I use some special kind of db.

I have the following two up and down files, created with luminus: 

`resources/migrations/20170426142711-add-rna-table.up.sql`,
`resources/migrations/20170426142711-add-rna-table.down.sql` 

They look like the following:

```
CREATE TABLE RNADB
(id VARCHAR(20) PRIMARY KEY,
FDR DECIMAL,
contrast1 DECIMAL,
contrast2 DECIMAL,
contrast3 DECIMAL,
info VARCHAR(30));
```
and

```
DROP TABLE IF EXISTS RNADB;
```

I have made changes to the up file, so I want to rerun the migration. However, when I try to do so, I get a table already exists error. I have tried rolling back, up, down and forth and also the migratus down command, but nothing seems to help. How do I delete the database I created so I can migrate it again? 

```
lein run migrate
[2017-04-26 14:47:17,235][DEBUG][org.jboss.logging] Logging Provider: org.jboss.logging.Log4jLoggerProvider
[2017-04-26 14:47:20,732][INFO][migratus.core] Starting migrations
[2017-04-26 14:47:23,354][INFO][migratus.core] Running up for [20170426142711]
[2017-04-26 14:47:23,355][INFO][migratus.core] Up 20170426142711-add-rna-table
[2017-04-26 14:47:23,359][DEBUG][migratus.database] found 1 up migrations
[2017-04-26 14:47:23,388][INFO][migratus.core] Ending migrations
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Table "RNADB" already exists; SQL statement:
CREATE TABLE RNADB
(id VARCHAR(20) PRIMARY KEY,
FDR DECIMAL,
contrast1 DECIMAL,
contrast2 DECIMAL,
contrast3 DECIMAL,
info VARCHAR(30));
 [42101-191], compiling:(/private/var/folders/y3/7657qc4x24l1pydf2_xgd05m0000gn/T/form-init2480066796860591165.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.h2.jdbc.JdbcSQLException: Table "RNADB" already exists; SQL statement:
CREATE TABLE RNADB
(id VARCHAR(20) PRIMARY KEY,
FDR DECIMAL,
contrast1 DECIMAL,
contrast2 DECIMAL,
contrast3 DECIMAL,
info VARCHAR(30));
 [42101-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__14183.invoke(jdbc.clj:753)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:595)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:752)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:748)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:786)
	at clojure.java.jdbc$db_do_prepared.doInvoke(jdbc.clj:770)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$apply.invoke(core.clj:641)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:781)
	at clojure.java.jdbc$db_do_prepared.doInvoke(jdbc.clj:770)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_$fn__14522.invoke(database.clj:61)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:595)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_.invokeStatic(database.clj:54)
	at migratus.database$up_STAR_.invoke(database.clj:53)
	at migratus.database.Migration.up(database.clj:150)
	at migratus.core$up_STAR_.invokeStatic(core.clj:47)
	at migratus.core$up_STAR_.invoke(core.clj:45)
	at migratus.core$migrate_up_STAR_.invokeStatic(core.clj:54)
	at migratus.core$migrate_up_STAR_.invoke(core.clj:49)
	at migratus.core$migrate_STAR_.invokeStatic(core.clj:58)
	at migratus.core$migrate_STAR_.invoke(core.clj:56)
	at migratus.core$run.invokeStatic(core.clj:25)
	at migratus.core$run.invoke(core.clj:21)
	at migratus.core$migrate.invokeStatic(core.clj:63)
	at migratus.core$migrate.invoke(core.clj:60)
	at rnadb.db.migrations$migrate.invokeStatic(migrations.clj:17)
	at rnadb.db.migrations$migrate.invoke(migrations.clj:10)
	at rnadb.core$_main.invokeStatic(core.clj:40)
	at rnadb.core$_main.doInvoke(core.clj:37)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at user$eval12695.invokeStatic(form-init2480066796860591165.clj:1)
	at user$eval12695.invoke(form-init2480066796860591165.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
```

Edit: The following did not work either. I am stumped:

```
endrebakkenstovner@ans-180249 ~/t/c/l/rnadb> lein migratus down 20170426142711
rolling back (20170426142711)
[2017-04-26 15:12:37,748][DEBUG][org.jboss.logging] Logging Provider: org.jboss.logging.Log4jLoggerProvider
[2017-04-26 15:12:39,987][INFO][migratus.core] Starting migrations
[2017-04-26 15:12:43,281][INFO][migratus.core] Ending migrations

endrebakkenstovner@ans-180249 ~/t/c/l/rnadb> lein migratus up 20170426142711
migrating (20170426142711)
[2017-04-26 15:13:27,642][DEBUG][org.jboss.logging] Logging Provider: org.jboss.logging.Log4jLoggerProvider
[2017-04-26 15:13:30,044][INFO][migratus.core] Starting migrations
[2017-04-26 15:13:33,551][INFO][migratus.core] Running up for [20170426142711]
[2017-04-26 15:13:33,552][INFO][migratus.core] Up 20170426142711-add-rna-table
[2017-04-26 15:13:33,556][DEBUG][migratus.database] found 1 up migrations
[2017-04-26 15:13:33,584][INFO][migratus.core] Ending migrations
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Table "RNADB" already exists; SQL statement:
CREATE TABLE RNADB
(id VARCHAR(20) PRIMARY KEY,
FDR DECIMAL,
contrast1 DECIMAL,
contrast2 DECIMAL,
contrast3 DECIMAL,
info VARCHAR(30));
 [42101-191], compiling:(/private/var/folders/y3/7657qc4x24l1pydf2_xgd05m0000gn/T/form-init21037636132883355.clj:1:123)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.h2.jdbc.JdbcSQLException: Table "RNADB" already exists; SQL statement:
CREATE TABLE RNADB
(id VARCHAR(20) PRIMARY KEY,
FDR DECIMAL,
contrast1 DECIMAL,
contrast2 DECIMAL,
contrast3 DECIMAL,
info VARCHAR(30));
 [42101-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__13180.invoke(jdbc.clj:753)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:595)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:752)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:748)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:786)
	at clojure.java.jdbc$db_do_prepared.doInvoke(jdbc.clj:770)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$apply.invoke(core.clj:641)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:781)
	at clojure.java.jdbc$db_do_prepared.doInvoke(jdbc.clj:770)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_$fn__13519.invoke(database.clj:61)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:595)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_.invokeStatic(database.clj:54)
	at migratus.database$up_STAR_.invoke(database.clj:53)
	at migratus.database.Migration.up(database.clj:150)
	at migratus.core$up_STAR_.invokeStatic(core.clj:47)
	at migratus.core$up_STAR_.invoke(core.clj:45)
	at migratus.core$migrate_up_STAR_.invokeStatic(core.clj:54)
	at migratus.core$migrate_up_STAR_.invoke(core.clj:49)
	at migratus.core$run_up.invokeStatic(core.clj:69)
	at migratus.core$run_up.invoke(core.clj:65)
	at migratus.core$run.invokeStatic(core.clj:25)
	at migratus.core$run.invoke(core.clj:21)
	at migratus.core$up.invokeStatic(core.clj:75)
	at migratus.core$up.doInvoke(core.clj:71)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at user$eval13840.invokeStatic(form-init21037636132883355.clj:1)
	at user$eval13840.invoke(form-init21037636132883355.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Subprocess failed 
```

**Comment by yogthos** [comment]
It doesn't look like migratus is recognizing your down migration:

```
lein migratus down 20170426142711
rolling back (20170426142711)
[2017-04-26 15:12:37,748][DEBUG][org.jboss.logging] Logging Provider: org.jboss.logging.Log4jLoggerProvider
[2017-04-26 15:12:39,987][INFO][migratus.core] Starting migrations
[2017-04-26 15:12:43,281][INFO][migratus.core] Ending migrations
```

Your process seems to be correct. When you run an up migration, you should be able to run the corresponding down migration to roll it back. Migratus uses a database table to keep track of what migrations have been applied successfully. It looks like it doesn't recognize the migration as having been applied successfully and isn't running the down script for it.

I tried with a fresh project just now, and here's what my output looks like:

```
lein migratus migrate
migrating all outstanding migrations
2017-04-26 10:40:49,003 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
2017-04-26 10:40:51,040 [main] INFO  migratus.core - Starting migrations
2017-04-26 10:40:51,294 [main] INFO  migratus.core - Running up for [20170426103242]
2017-04-26 10:40:51,295 [main] INFO  migratus.core - Up 20170426103242-add-users-table
2017-04-26 10:40:51,309 [main] DEBUG migratus.database - found 1 up migrations
2017-04-26 10:40:51,314 [main] DEBUG migratus.database - marking 20170426103242 complete
2017-04-26 10:40:51,320 [main] INFO  migratus.core - Ending migrations

lein migratus down 20170426103242
rolling back (20170426103242)
2017-04-26 10:41:24,560 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
2017-04-26 10:41:26,741 [main] INFO  migratus.core - Starting migrations
2017-04-26 10:41:27,000 [main] INFO  migratus.core - Running down for [20170426103242]
2017-04-26 10:41:27,001 [main] INFO  migratus.core - Down 20170426103242-add-users-table
2017-04-26 10:41:27,015 [main] DEBUG migratus.database - found 1 down migrations
2017-04-26 10:41:27,019 [main] DEBUG migratus.database - marking 20170426103242 not complete
2017-04-26 10:41:27,025 [main] INFO  migratus.core - Ending migrations

migratus migrate
migrating all outstanding migrations
2017-04-26 10:43:01,194 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
2017-04-26 10:43:02,980 [main] INFO  migratus.core - Starting migrations
2017-04-26 10:43:03,232 [main] INFO  migratus.core - Running up for [20170426103242]
2017-04-26 10:43:03,233 [main] INFO  migratus.core - Up 20170426103242-add-users-table
2017-04-26 10:43:03,250 [main] DEBUG migratus.database - found 1 up migrations
2017-04-26 10:43:03,255 [main] DEBUG migratus.database - marking 20170426103242 complete
2017-04-26 10:43:03,263 [main] INFO  migratus.core - Ending migrations
```
Th H2 database is stored in a file. You should see a couple of files that look like `myapp_dev.db.mv.db` and `myapp_dev.db.trace.db` in your project. If you remove those, migratus should recreate the database for you.

**Comment by endrebak** [comment]
Thanks for the help.
Love what you are doing for the Clojure ecosystem btw!

**Comment by yogthos** [comment]
Thanks :)
