### ISSUE TITLE
migrations failed but migratus gives me a useless stacktrace

### ISSUE THREAD

**Issue by danlarkin** [yogthos/migratus#16]
Using migratus-0.5.0 I get this output while trying to run my migrations:

```

2012-11-24 10:10:57,082 | INFO  | migratus.database | creating migration table 'schema_migrations'
2012-11-24 10:10:57,152 | INFO  | migratus.core | Starting migrations
2012-11-24 10:10:57,445 | INFO  | migratus.core | Running up for [20121124100400]
2012-11-24 10:10:57,446 | INFO  | migratus.core | Up 20121124100400-add-everything
2012-11-24 10:11:01,811 | INFO  | migratus.core | Ending migrations
Exception in thread "main" java.sql.BatchUpdateException: Batch entry 1 <unknown> was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2621)
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleCommandStatus(AbstractJdbc2Statement.java:2592)
	at org.postgresql.core.v3.QueryExecutorImpl.interpretCommandStatus(QueryExecutorImpl.java:2150)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1804)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:407)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2754)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:298)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:418)
	at clojure.java.jdbc$do_commands$fn__973.invoke(jdbc.clj:430)
	at clojure.java.jdbc$transaction_STAR_.invoke(jdbc.clj:384)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:429)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at migratus.database$up_STAR_$fn__13404.invoke(database.clj:50)
	at clojure.java.jdbc$transaction_STAR_.invoke(jdbc.clj:372)
	at migratus.database$up_STAR_.invoke(database.clj:44)
	at clojure.lang.AFn.applyToHelper(AFn.java:167)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:601)
	at robert.bruce$try_try_again$fn__13393.invoke(bruce.clj:118)
	at robert.bruce$retry.invoke(bruce.clj:94)
	at robert.bruce$retry$fn__13386.invoke(bruce.clj:109)
	at clojure.core$trampoline.invoke(core.clj:5575)
	at clojure.core$trampoline.doInvoke(core.clj:5580)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at robert.bruce$try_try_again.doInvoke(bruce.clj:118)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at migratus.database.Migration.up(database.clj:71)
	at migratus.core$up_STAR_.invoke(core.clj:37)
	at migratus.core$migrate_STAR_.invoke(core.clj:44)
	at migratus.core$migrate$fn__1200.invoke(core.clj:57)
	at migratus.core$run.invoke(core.clj:23)
	at migratus.core$migrate.invoke(core.clj:57)
	at megatron.db$db_init.invoke(db.clj:16)
	at clojure.lang.Var.invoke(Var.java:411)
	at carousel.module$init$fn__175.invoke(module.clj:28)
	at carousel.registry$do_registered.doInvoke(registry.clj:45)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at carousel.module$init.invoke(module.clj:28)
	at megatron.main$main.invoke(main.clj:7)
	at user$eval13326.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6501)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$eval_opt.invoke(main.clj:297)
	at clojure.main$initialize.invoke(main.clj:316)
	at clojure.main$null_opt.invoke(main.clj:349)
	at clojure.main$main.doInvoke(main.clj:427)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
```

**Comment by yogthos** [comment]
updated to handle wrapped execptions
