### ISSUE TITLE
Document or warn when migrations contain INSERT statements

### ISSUE THREAD

**Issue by sharms** [yogthos/migratus#25]
When using migrations combined with insert statements, an exception will be thrown.  May be good to outline this in the documentation:

201506300001-create-table.up.sql
```sql
CREATE TABLE IF NOT EXISTS variance (
       id SERIAL PRIMARY KEY NOT NULL,
       is_exception boolean DEFAULT false,
       is_obsolete boolean DEFAULT false,
       is_disabled boolean DEFAULT false
);

INSERT INTO variance (is_exception, is_obsolete, is_disabled) VALUES (false, false, false);
INSERT INTO variance (is_exception, is_obsolete, is_disabled) VALUES (true, false, false);
INSERT INTO variance (is_exception, is_obsolete, is_disabled) VALUES (true, true, false);
INSERT INTO variance (is_exception, is_obsolete, is_disabled) VALUES (true, true, true);
INSERT INTO variance (is_exception, is_obsolete, is_disabled) VALUES (false, true, false);
INSERT INTO variance (is_exception, is_obsolete, is_disabled) VALUES (false, true, true);
INSERT INTO variance (is_exception, is_obsolete, is_disabled) VALUES (false, false, true);
INSERT INTO variance (is_exception, is_obsolete, is_disabled) VALUES (true, false, true);
```

Results in:
```
Exception in thread "main" org.postgresql.util.PSQLException: Too many update results were returned., compiling:(/private/var/folders/sq/0nk_x07s751gqtcxkj92bxjr0000gn/T/form-init5811083923084408417.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.postgresql.util.PSQLException: Too many update results were returned.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleCommandStatus(AbstractJdbc2Statement.java:2714)
	at org.postgresql.core.v3.QueryExecutorImpl.interpretCommandStatus(QueryExecutorImpl.java:2252)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1884)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:401)
	at clojure.java.jdbc$db_do_commands$fn__24969.invoke(jdbc.clj:675)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:584)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:674)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:668)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_$fn__25194.invoke(database.clj:59)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:584)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_.invoke(database.clj:52)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at robert.bruce$try_try_again$fn__25180.invoke(bruce.clj:118)
	at robert.bruce$retry.invoke(bruce.clj:94)
	at robert.bruce$retry$fn__25173.invoke(bruce.clj:109)
	at clojure.core$trampoline.invoke(core.clj:6037)
	at clojure.core$trampoline.doInvoke(core.clj:6042)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at robert.bruce$try_try_again.doInvoke(bruce.clj:118)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at migratus.database.Migration.up(database.clj:148)
	at migratus.core$up_STAR_.invoke(core.clj:47)
	at migratus.core$migrate_up_STAR_.invoke(core.clj:54)
	at migratus.core$migrate_STAR_.invoke(core.clj:58)
	at migratus.core$run.invoke(core.clj:25)
	at migratus.core$migrate.invoke(core.clj:63)
	at techstack.db.migrations$migrate.invoke(migrations.clj:14)
	at techstack.core$_main.doInvoke(core.clj:37)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at user$eval58.invoke(form-init5811083923084408417.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
~~~

**Comment by yogthos** [comment]
You have to use the `--;;` separator between multiple statements as mentioned in the docs.
