### ISSUE TITLE
Migrations fail due to illegal path construction when packaged in jar

### ISSUE THREAD

**Issue by pcruche** [yogthos/migratus#267]
I'm using the library in an application packaged as uberjar, and run pending migrations on start. The migration files are located in the application resources. When running from the REPL, that works as expected. Packaged as .jar file, the library attempts to build an URI from a path that's invalid (containing '\' characters).

```
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\...\my-app-standalone.jar
        at java.base/java.net.URI$Parser.fail(Unknown Source)
        at java.base/java.net.URI$Parser.checkChars(Unknown Source)
        at java.base/java.net.URI$Parser.parse(Unknown Source)
        at java.base/java.net.URI.<init>(Unknown Source)
        at migratus.utils$script_excluded_QMARK_.invokeStatic(utils.clj:43)
        at migratus.utils$script_excluded_QMARK_.invoke(utils.clj:36)
        at migratus.migrations$find_migration_resources$iter__17465__17469$fn__17470.invoke(migrations.clj:98)
       ...
```

I'm on Windows, though I think that path would be invalid in other OSs as well.

The failing code is
```
(URI. (str "jar:file:" (.getName ^JarFile migration-dir)))
```

A possible solution would be to extract convert the jar file name and use the objects toURI-method:
```
(URI. (str "jar:" (-> migration-dir .getName io/file .toURI)))
```

**Comment by yogthos** [comment]
Maybe could this as a fallback to make sure there are no regressions from current functionality?

```clojure
(try
   (URI. (str "jar:file:" (.getName ^JarFile migration-dir)))
   (catch java.net.URISyntaxException _
     (URI. (str "jar:" (-> migration-dir .getName io/file .toURI)))))
```

**Comment by pcruche** [comment]
I also noticed I have a redundant call to the URI constructor.

**Comment by yogthos** [comment]
It might be needed to add the `jar:` bit actually. I've just pushed out `1.5.8` with the fix, let me know if it looks good.

**Comment by pcruche** [comment]
> It might be needed to add the `jar:` bit actually.
Yes, I got confused for a moment 👍

**Comment by pcruche** [comment]
Looking good, thank you
