### ISSUE TITLE
Feature request: Allow for multiple statements on a single migration file

### ISSUE THREAD

**Issue by ricardojmendez** [yogthos/migratus#29]
Migratus 0.8.1 fails when attempting to run a migration which contains multiple statements, for instance, two `CREATE TABLE` statements.

```
Exception in thread "main" org.postgresql.util.PSQLException: Too many update results were returned., compiling:(/private/var/folders/64/ckdtdxm14059n9wh8rhf1mvw0000gn/T/form-init7217067018953698863.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.postgresql.util.PSQLException: Too many update results were returned.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleCommandStatus(AbstractJdbc2Statement.java:2733)
	at org.postgresql.core.v3.QueryExecutorImpl.interpretCommandStatus(QueryExecutorImpl.java:2324)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1955)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:421)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2929)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:401)
	at clojure.java.jdbc$db_do_commands$fn__20246.invoke(jdbc.clj:675)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:584)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:674)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:668)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_$fn__20702.invoke(database.clj:62)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:584)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_.invoke(database.clj:55)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at robert.bruce$try_try_again$fn__20457.invoke(bruce.clj:118)
	at robert.bruce$retry.invoke(bruce.clj:94)
	at robert.bruce$retry$fn__20450.invoke(bruce.clj:109)
	at clojure.core$trampoline.invoke(core.clj:6037)
	at clojure.core$trampoline.doInvoke(core.clj:6042)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at robert.bruce$try_try_again.doInvoke(bruce.clj:118)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at migratus.database.Migration.up(database.clj:151)
	at migratus.core$up_STAR_.invoke(core.clj:47)
	at migratus.core$migrate_up_STAR_.invoke(core.clj:54)
	at migratus.core$migrate_STAR_.invoke(core.clj:58)
	at migratus.core$run.invoke(core.clj:25)
(etc)
```

**Comment by yogthos** [comment]
are you using the `--;;` separator between multiple statements as indicated in the [docs](https://github.com/yogthos/migratus#databases)?

**Comment by ricardojmendez** [comment]
Eep. It appears I skipped that. Closing, thanks!

**Comment by yogthos** [comment]
I'll update the docs to make that a bit more prominent ;)
