### ISSUE TITLE
Up migrations failing with org.postgresql/postgresql "9.4-1203-jdbc41"

### ISSUE THREAD

**Issue by nside** [yogthos/migratus#41]
They work fine with 9.4-1201-jdbc41 but with the latest JDBC driver version 9.4-1203-jdbc41 I get this error when running an up migration:
```
Exception in thread "main" org.postgresql.util.PSQLException: Too many update results were returned., compiling:(/private/var/folders/3s/ksknbjrd47jgbf95vzr_bx0w0000gn/T/form-init5347993960870637955.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.postgresql.util.PSQLException: Too many update results were returned.
```

**Comment by yogthos** [comment]
Could you paste the sql that's causing the error, one thing to note is that you have to use `--;;` to separate multiple migration statements in the same file.

**Comment by nside** [comment]
There's a single statement in the file and it fails on any of my existing migrations.
Example of a failing one: `ALTER TABLE xxx ALTER COLUMN yyy SET DATA TYPE zzz;`

**Comment by yogthos** [comment]
Ok, I've managed to reproduce the problem locally as well.

**Comment by nside** [comment]
I think I isolated it to the query ending with ;

**Comment by yogthos** [comment]
I just pushed a fix, could you try locally to see if it helps in your case?

**Comment by nside** [comment]
Yes I just verified the fix.
Great execution sir!

**Comment by nside** [comment]
Are you pushing 0.8.6 to clojars?

**Comment by yogthos** [comment]
just pushed it out :)

**Comment by nside** [comment]
nice thanks!

**Comment by yogthos** [comment]
:+1:

**Comment by node13h** [comment]
same issue with down migrations

**Comment by yogthos** [comment]
That makes sense and I completely forgot to check for that when I did the original fix. I just checked in a change for that, could you test to confirm that it addresses the issue and I can push it out.
