### ISSUE TITLE
Single-statement rollback migration failing with "Too many update results were returned"

### ISSUE THREAD

**Issue by node13h** [yogthos/migratus#42]
Down file contains single statement ```DROP TABLE users;```
Using org.postgresql/postgresql "9.4-1203-jdbc41"

When I remove semicolon - rollback completes successfully.

```
02:26:51.002 [main] INFO  migratus.core - Starting migrations
02:26:51.421 [main] INFO  migratus.core - Running down for [20151007011602]
02:26:51.422 [main] INFO  migratus.core - Down 20151007011602-add-users-table
02:26:51.436 [main] DEBUG migratus.database - found 1 down migrations
02:26:52.470 [main] DEBUG migratus.database - found 1 down migrations
02:26:55.204 [main] DEBUG migratus.database - found 1 down migrations
02:26:55.212 [main] INFO  migratus.core - Ending migrations
Exception in thread "main" org.postgresql.util.PSQLException: Too many update results were returned., compiling:(/tmp/form-init6425292863827031544.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.postgresql.util.PSQLException: Too many update results were returned.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleCommandStatus(AbstractJdbc2Statement.java:2688)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:338)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2898)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:401)
	at clojure.java.jdbc$db_do_commands$fn__807.invoke(jdbc.clj:675)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:584)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:674)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.java.jdbc$db_do_commands.doInvoke(jdbc.clj:668)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$down_STAR_$fn__1276.invoke(database.clj:73)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:584)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$down_STAR_.invoke(database.clj:66)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at robert.bruce$try_try_again$fn__1018.invoke(bruce.clj:118)
	at robert.bruce$retry.invoke(bruce.clj:94)
	at robert.bruce$retry$fn__1011.invoke(bruce.clj:109)
	at clojure.core$trampoline.invoke(core.clj:6037)
	at clojure.core$trampoline.doInvoke(core.clj:6042)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at robert.bruce$try_try_again.doInvoke(bruce.clj:118)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at migratus.database.Migration.down(database.clj:156)
	at migratus.core$run_down.invoke(core.clj:87)
	at migratus.core$rollback_STAR_.invoke(core.clj:96)
	at migratus.core$run.invoke(core.clj:25)
	at migratus.core$rollback.invoke(core.clj:106)
	at user$eval1567.invoke(form-init6425292863827031544.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
Subprocess failed
```

**Comment by yogthos** [comment]
appears related to https://github.com/yogthos/migratus/issues/41#issuecomment-146034134 and the fix should address both

**Comment by node13h** [comment]
Thanks for the 76b71e102ecc2ebc7d2ba0ab6c09d3b1446c4fe4
Hope to see 0.8.7 at clojars soon :)

**Comment by yogthos** [comment]
perfect just pushed to clojars
