### ISSUE TITLE
When there's an syntax error, a partial migration is left applied

### ISSUE THREAD

**Issue by pupeno** [yogthos/migratus#48]
I recently experienced a problem in which I have an up migration that looks something like this:

```sql
DROP INDEX features_id
--;;
DROP INDEX features_name
--;;
DROP INDEX features_slug
--;;
ARBITRARY SYNTAX ERROR
```
when I tried running it, this is the error I got:

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: index "features_id" does not exist, compiling:(/private/var/folders/k9/pgnpg2h92bv157mw70mhznk80000gn/T/form-init4702570188881465620.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.postgresql.util.PSQLException: ERROR: index "features_id" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__11756.invoke(jdbc.clj:753)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:595)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:752)
	at clojure.java.jdbc$db_do_prepared.doInvoke(jdbc.clj:786)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.java.jdbc$db_do_prepared.doInvoke(jdbc.clj:781)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_$fn__32126.invoke(database.clj:62)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:595)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_.invoke(database.clj:55)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at robert.bruce$try_try_again$fn__32112.invoke(bruce.clj:118)
	at robert.bruce$retry.invoke(bruce.clj:94)
	at robert.bruce$retry$fn__32105.invoke(bruce.clj:109)
	at clojure.core$trampoline.invoke(core.clj:6037)
	at clojure.core$trampoline.doInvoke(core.clj:6042)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at robert.bruce$try_try_again.doInvoke(bruce.clj:118)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at migratus.database.Migration.up(database.clj:151)
	at migratus.core$up_STAR_.invoke(core.clj:47)
	at migratus.core$migrate_up_STAR_.invoke(core.clj:54)
	at migratus.core$migrate_STAR_.invoke(core.clj:58)
	at migratus.core$run.invoke(core.clj:25)
	at migratus.core$migrate.invoke(core.clj:63)
	at ninjatools.db.migrations$migrate.invoke(migrations.clj:19)
	at ninjatools.core$_main.doInvoke(core.clj:40)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at user$eval58.invoke(form-init4702570188881465620.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
```

```features_id``` definitely existed before running this migration and also there's no mention of the syntax error. If I look at the database now, I can see that ```features_id``` is indeed gone but in ```schema_migrations```, this migration doesn't look like it was applied.

I turned on logging in PostgreSQL and this is what I found:

```
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>: BEGIN
LOG:  execute <unnamed>: SELECT * from schema_migrations WHERE id=$1
DETAIL:  parameters: $1 = '20151106134834'
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>:

        DROP INDEX features_id

LOG:  execute S_1: COMMIT
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>: BEGIN
LOG:  execute <unnamed>: DROP INDEX features_name

LOG:  execute S_1: COMMIT
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>: BEGIN
LOG:  execute <unnamed>: DROP INDEX features_slug

LOG:  execute S_1: COMMIT
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>: BEGIN
ERROR:  syntax error at or near "ARBITRARY" at character 1
STATEMENT:  ARBITRARY SYNTAX ERROR

LOG:  execute S_2: ROLLBACK
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>: BEGIN
LOG:  execute <unnamed>: SELECT * from schema_migrations WHERE id=$1
DETAIL:  parameters: $1 = '20151106134834'
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>:

        DROP INDEX features_id

ERROR:  index "features_id" does not exist
STATEMENT:

        DROP INDEX features_id

LOG:  execute S_2: ROLLBACK
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>: BEGIN
LOG:  execute <unnamed>: SELECT * from schema_migrations WHERE id=$1
DETAIL:  parameters: $1 = '20151106134834'
LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
LOG:  execute <unnamed>:

        DROP INDEX features_id

ERROR:  index "features_id" does not exist
STATEMENT:

        DROP INDEX features_id

LOG:  execute S_2: ROLLBACK
```

migratus is somehow trying to run the migration again and not properly rollbacking the whole migration.

**Comment by yogthos** [comment]
I probably won't have a chance to look in the near future, if you get a chance to dig a bit deeper in the meantime let me know.

**Comment by yogthos** [comment]
should be addressed by https://github.com/yogthos/migratus/pull/51
