### ISSUE TITLE
Can show friendly error message that can point which sql file and line cause error?

### ISSUE THREAD

**Issue by oscnet** [yogthos/migratus#60]
I have several big migrate files, then when it's has error, it's hard to find out which cause errors.

````
oscardeiMac:migrations oscar$ lein migratus migrate
migrating all outstanding migrations
16-Feb-25 08:40:36 oscardeiMac.local INFO [slf4j-timbre.adapter] - Starting migrations
16-Feb-25 08:40:36 oscardeiMac.local INFO [slf4j-timbre.adapter] - creating migration table 'schema_migrations'
16-Feb-25 08:40:36 oscardeiMac.local WARN [slf4j-timbre.adapter] - '20150320103048417-update-trigger.clj' does not appear to be a valid migration
16-Feb-25 08:40:36 oscardeiMac.local INFO [slf4j-timbre.adapter] - Running up for [20150318161224442 20150811205628841 20150813161002387 20150814200402283 20160207072921680]
16-Feb-25 08:40:36 oscardeiMac.local INFO [slf4j-timbre.adapter] - Up 20150318161224442-base
16-Feb-25 08:40:36 oscardeiMac.local DEBUG [slf4j-timbre.adapter] - found 48 up migrations
16-Feb-25 08:40:36 oscardeiMac.local INFO [slf4j-timbre.adapter] - Ending migrations
Exception in thread "main" com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 11, compiling:(/private/var/folders/09/1sxxd1nn2mj3lnv6f90kstb40000gn/T/form-init5442890000147498866.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 11
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2113)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2049)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2034)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__367.invoke(jdbc.clj:753)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:595)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:752)
	at clojure.java.jdbc$db_do_prepared.doInvoke(jdbc.clj:786)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:636)
	at clojure.java.jdbc$db_do_prepared.doInvoke(jdbc.clj:781)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_$fn__549.invoke(database.clj:61)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:595)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at migratus.database$up_STAR_.invoke(database.clj:54)
	at migratus.database.Migration.up(database.clj:163)
	at migratus.core$up_STAR_.invoke(core.clj:47)
	at migratus.core$migrate_up_STAR_.invoke(core.clj:54)
	at migratus.core$migrate_STAR_.invoke(core.clj:58)
	at migratus.core$run.invoke(core.clj:25)
	at migratus.core$migrate.invoke(core.clj:63)
	at user$eval90.invoke(form-init5442890000147498866.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
Subprocess failed
````

**Comment by oscnet** [comment]
or simply  just show the sql syntax that cause the error may great help.

**Comment by yogthos** [comment]
Yeah, it would definitely be helpful to log what statement failed when it fails.

**Comment by yogthos** [comment]
ok I just pushed a [new version with a fix](https://github.com/yogthos/migratus/commit/6e6c2299d1e30e1fb897433f85f4127346ddfa3f), if you can try it locally to confirm that it solves the problem I can push to Clojars

**Comment by oscnet** [comment]
ok, it worked , 
other question  the migrate will not stop when it get one error , continue execute the other sql cmd,  so if the sql file has many sql command, it will cause too many errors.

**Comment by yogthos** [comment]
should be fixed by https://github.com/yogthos/migratus/commit/b9f1012624823dfe025420763f1461b345fb96f3
