### ISSUE TITLE
migrates reset not worked now

### ISSUE THREAD

**Issue by oscnet** [yogthos/migratus#62]
oscardeiMac:lspatent oscar$ lein migratus reset
resetting the database
16-Feb-25 10:44:01 oscardeiMac.local INFO [slf4j-timbre.adapter] - Starting migrations
16-Feb-25 10:44:01 oscardeiMac.local INFO [slf4j-timbre.adapter] - Ending migrations
Exception in thread "main" java.lang.ClassCastException: migratus.database.Database cannot be cast to clojure.lang.IFn, compiling:(/private/var/folders/09/1sxxd1nn2mj3lnv6f90kstb40000gn/T/form-init3851805279291647805.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassCastException: migratus.database.Database cannot be cast to clojure.lang.IFn
	at migratus.core$reset_STAR_.invoke(core.clj:104)
	at migratus.core$run.invoke(core.clj:25)
	at migratus.core$reset.invoke(core.clj:116)
	at user$eval334.invoke(form-init3851805279291647805.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
Subprocess failed

**Comment by yogthos** [comment]
looks like that was an unrelated bug fixed by this pr https://github.com/yogthos/migratus/pull/61 and I just pushed out `0.8.13`, let me know if everything looks good

**Comment by oscnet** [comment]
tested and  looks good

**Comment by yogthos** [comment]
perfect
