### ISSUE TITLE
Migratus throws NullPointerException when database is down

### ISSUE THREAD

**Issue by theronic** [yogthos/migratus#75]
Migratus throws a NullPointerException if target database is down. If you don't know your DB is down, you might think something is wrong with your connection string or migration. A clearer SQL-related exception would help to diagnose errors:

```
java.lang.NullPointerException:
                   migratus.database/connect*      database.clj:  194
           migratus.database.Database/connect      database.clj:  274
                            migratus.core/run          core.clj:   24
                           migratus.core/down          core.clj:   93
                                          ...
```

**Comment by yogthos** [comment]
that makes sense to me

**Comment by yogthos** [comment]
Hmm, it does look like there's a [`try/catch` around `connect*`](https://github.com/yogthos/migratus/blob/20a8fbd4364196b8b3c7292b246dd8aa12ec42fa/src/migratus/database.clj#L193) already, are you on the latest version?

**Comment by jumarko** [comment]
Although there's still some NPE deep down in the stack, the top-level exception is very readable I guess (at least for PostgreSQL):
```
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```
I think this issue could be closed.

This is the whole stack
```
2017-03-10 05:37:14,944 [main] ERROR migratus.database - Error creating DB connection for jdbc:postgresql://localhost/my_bookshelf_dev?user=bookworm&password=password
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.Driver.makeConnection(Driver.java:404) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.Driver.connect(Driver.java:272) ~[postgresql-9.4.1212.jar:9.4.1212]
        at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_40]
        at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_40]
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:272) ~[na:na]
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193) ~[na:na]
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:256) ~[na:na]
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193) ~[na:na]
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:259) ~[na:na]
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193) ~[na:na]
        at migratus.database$connect_STAR_$fn__22020.invoke(database.clj:220) ~[na:na]
        at migratus.database$connect_STAR_.invokeStatic(database.clj:219) [na:na]
        at migratus.database$connect_STAR_.invoke(database.clj:217) [na:na]
        at migratus.database.Database.connect(database.clj:338) [na:na]
        at migratus.core$run.invokeStatic(core.clj:24) [na:na]
        at migratus.core$run.invoke(core.clj:21) [na:na]
        at migratus.core$migrate.invokeStatic(core.clj:66) [na:na]
        at migratus.core$migrate.invoke(core.clj:63) [na:na]
        at user$eval22564.invokeStatic(form-init4297225071553154250.clj:1) [na:na]
        at user$eval22564.invoke(form-init4297225071553154250.clj:1) [na:na]
        at clojure.lang.Compiler.eval(Compiler.java:6927) [clojure-1.8.0.jar:na]
        at clojure.lang.Compiler.eval(Compiler.java:6917) [clojure-1.8.0.jar:na]
        at clojure.lang.Compiler.load(Compiler.java:7379) [clojure-1.8.0.jar:na]
        at clojure.lang.Compiler.loadFile(Compiler.java:7317) [clojure-1.8.0.jar:na]
        at clojure.main$load_script.invokeStatic(main.clj:275) [clojure-1.8.0.jar:na]
        at clojure.main$init_opt.invokeStatic(main.clj:277) [clojure-1.8.0.jar:na]
        at clojure.main$init_opt.invoke(main.clj:277) [clojure-1.8.0.jar:na]
        at clojure.main$initialize.invokeStatic(main.clj:308) [clojure-1.8.0.jar:na]
        at clojure.main$null_opt.invokeStatic(main.clj:342) [clojure-1.8.0.jar:na]
        at clojure.main$null_opt.invoke(main.clj:339) [clojure-1.8.0.jar:na]
        at clojure.main$main.invokeStatic(main.clj:421) [clojure-1.8.0.jar:na]
        at clojure.main$main.doInvoke(main.clj:384) [clojure-1.8.0.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.8.0.jar:na]
        at clojure.lang.Var.invoke(Var.java:383) [clojure-1.8.0.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.8.0.jar:na]
        at clojure.lang.Var.applyTo(Var.java:700) [clojure-1.8.0.jar:na]
        at clojure.main.main(main.java:37) [clojure-1.8.0.jar:na]
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_40]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_40]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_40]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_40]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_40]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_40]
        at org.postgresql.core.PGStream.<init>(PGStream.java:61) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144) ~Exception in thread "main" java.lang.NullPointerException, compiling:(/private/var/folders/hn/tgwyrdmj1tb5pmmbdkd1g_qc0000gn/T/form-init4297225071553154250.clj:1:125)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
        at migratus.database$connect_STAR_.invokeStatic(database.clj:223)
        at migratus.database$connect_STAR_.invoke(dat[postgresql-9.4.1212.jar:9.4.1212]
        ... 39 common frames omitted
2017-03-10 05:37:14,945 [main] INFO  migratus.core - Ending migrations
abase.clj:217)
        at migratus.database.Database.connect(database.clj:338)
        at migratus.core$run.invokeStatic(core.clj:24)
        at migratus.core$run.invoke(core.clj:21)
        at migratus.core$migrate.invokeStatic(core.clj:66)
        at migratus.core$migrate.invoke(core.clj:63)
        at user$eval22564.invokeStatic(form-init4297225071553154250.clj:1)
        at user$eval22564.invoke(form-init4297225071553154250.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 14 more
Subprocess failed

```

**Comment by yogthos** [comment]
Agreed, top level exception message is pretty clear.
