### ISSUE TITLE
Error migrating with 0.8.22

### ISSUE THREAD

**Issue by ArseAssassin** [yogthos/migratus#79]
When running any migration after `schema_migrations` has been created, I'm getting the following error message:

`Exception in thread "main" org.postgresql.util.PSQLException: ERROR: relation "schema_migrations" already exists, compiling:(/tmp/form-init7884403776757165926.clj:1:73)`

Using `[org.postgresql/postgresql "9.4-1201-jdbc41"]`. Everything seems to work fine in version 0.8.18.

**Comment by yogthos** [comment]
Is this happening on a fresh project. I'm not able to reproduce the issue locally. It looks like migratus is attempting to create a migrations table and you already have one.

**Comment by ArseAssassin** [comment]
Yes, this is a project I just started.

**Comment by yogthos** [comment]
Hmm, could you possibly post a repo with the problem. I just tried with a new project and didn't see the issue. Can you also check whether the `schema_migrations` migration already exists in the db.

**Comment by ArseAssassin** [comment]
Created a new project to reproduce the issue.
```clojure
(defproject test-migratus "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :plugins [[migratus-lein "0.3.6"]]
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [migratus "0.8.24"]
                 [org.postgresql/postgresql "9.4-1201-jdbc41"]]
  :main ^:skip-aot test-migratus.core
  :migratus {:store :database
             :migration-dir "migrations"
             :db "jdbc:postgresql://localhost/test_migratus?user=user&password=password&stringtype=unspecified"}
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

```
test_migratus=# \dt
               List of relations
 Schema |       Name        | Type  |  Owner   
--------+-------------------+-------+----------
 public | schema_migrations | table | postgres
(1 row)

test_migratus=# SELECT VERSION();
                                                version                                                
-------------------------------------------------------------------------------------------------------
 PostgreSQL 9.3.11 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit
(1 row)

test_migratus=# 
```

```
tuomas@tuomas-HP-EliteBook-8470p ~/p/t/test-migratus> lein migratus reset
resetting the database
Jun 13, 2016 9:31:22 PM clojure.tools.logging$eval293$fn__297 invoke
INFO: Starting migrations
Jun 13, 2016 9:31:22 PM clojure.tools.logging$eval293$fn__297 invoke
INFO: creating migration table 'schema_migrations'
Jun 13, 2016 9:31:22 PM clojure.tools.logging$eval293$fn__297 invoke
INFO: Ending migrations
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: relation "schema_migrations" already exists, compiling:(/tmp/form-init8391266422745155354.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "schema_migrations" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:421)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2929)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:426)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:419)
	at clojure.java.jdbc$db_do_commands$fn__832.invoke(jdbc.clj:721)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_do_commands.invokeStatic(jdbc.clj:720)
	at clojure.java.jdbc$db_do_commands.invoke(jdbc.clj:705)
	at clojure.java.jdbc$db_do_commands.invokeStatic(jdbc.clj:711)
	at clojure.java.jdbc$db_do_commands.invoke(jdbc.clj:705)
	at migratus.database$init_schema_BANG_$fn__1222.invoke(database.clj:253)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at migratus.database$init_schema_BANG_.invokeStatic(database.clj:249)
	at migratus.database$init_schema_BANG_.invoke(database.clj:248)
	at migratus.database.Database.connect(database.clj:291)
	at migratus.core$run.invokeStatic(core.clj:24)
	at migratus.core$run.invoke(core.clj:21)
	at migratus.core$reset.invokeStatic(core.clj:115)
	at migratus.core$reset.invoke(core.clj:111)
	at user$eval1314.invokeStatic(form-init8391266422745155354.clj:1)
	at user$eval1314.invoke(form-init8391266422745155354.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Subprocess failed
```

**Comment by yogthos** [comment]
Hmm, not sure why this is happening for you, since the first thing `init-schema!` does is [check whether the table exists](https://github.com/yogthos/migratus/blob/2c259648c7f49de7ebc45d73240cca36c429fe58/src/migratus/database.clj#L248). Perhaps the logic for finding the table i not working correctly/

**Comment by yogthos** [comment]
OK I've got the issue reproduced, it is the problem with the logic finding the table, just working on a fix here.

**Comment by yogthos** [comment]
Looks like this was related to pr #70 where the schema is used to restrict the lookup. When the connection doesn't specify the schema, then the lookup fails and you get the error. I just released a new version that will fallback to doing a lookup using the schema and if it fails to do another without it. Let me know if that works for you with `[migratus "0.8.25"]`.

**Comment by ArseAssassin** [comment]
Yes, works like a charm. Thank you! :)
